<p>Las excepciones se pueden controlar, esto es, no necesariamente tienen que interrumpir la ejecución del programa. Para controlar las excepciones lo que se hace es capturarlas.</p>

<div class="container">
    <pre data-code="https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/POO/temas/31/2/<lenguaje>/0.<lenguaje>"></pre>
</div>

<p>Cuando se produce una excepción dentro del <code>código a controlar</code>, se interrumpe la ejecución de ese bloque de código pero la ejecución continúa en el <code>código a ejecutar en caso de excepción</code>.</p>

<p>En el siguiente ejemplo se pide al usuario un número que se usa para dividir 100. Si el número introducido es 0 se producirá una excepción que es capturada para evitar que se interrumpa la ejecución y mostrar el mensaje de error <code>no se puede dividir entre 0</code></p>

<div class="container">
    <pre data-code="https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/POO/temas/31/2/<lenguaje>/1.<lenguaje>"></pre>
    <pre data-code="https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/POO/temas/31/2/1.txt"></pre>
</div>

<p>Es posible indicar qué tipo de excepción se captura y capturar diferentes tipos de excepciones con varios bloques.</p>

<div class="container">
    <pre data-code="https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/POO/temas/31/2/<lenguaje>/2.<lenguaje>"></pre>
    <pre data-code="https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/POO/temas/31/2/2.txt"></pre>
</div>
